version: "2.5"

services:
    server1:
        image: ivansu995/ssh-server
        volumes:
            - students:/home/students
        ports:
            - "30000:22"

    server2:
        image: ivansu995/ssh-server
        volumes:
            - students:/home/students
        ports:
            - "30001:22"

volumes:
    students:
        driver: local
